Pequena alteração no README.md
unb-cic-esw/data-viz pull request #32
Opened 2018-06-12 16:34 UTC by rodrigofegui

Add:
    - Dicas para a preparação do ambiente no Ubuntu, por ser tantos passos específicos.

2018-06-12 22:40 UTC, mikaelmello requested changes
Toda a parte da biblioteca Cairo, NodeJS e MongoDB já tem explicações em "Pré-requisitos".

2018-06-13 00:41 UTC, rodrigofegui commented
Os procedimentos base das referências existentes não foram suficientes para ninguém que utiliza o Ubuntu.

2018-06-13 00:42 UTC, mikaelmello commented
Qual parte deu erro? Porque uso Ubuntu e foi literalmente só aquilo kkk

2018-06-13 00:48 UTC, mikaelmello commented
Mas eu entendo sobre outras bibliotecas que precisam como `libjpeg-dev` (e seus gif/png equivalentes), `g++` e `build-essentials`.

O resto de NVM e Mongo acho desnecessário

2018-06-15 01:52 UTC, rodrigofegui commented
Os passos para o NVM e o Mongo me facilitaram o acesso, mas posso tirar. O Cairo que precisa muito

2018-06-15 03:57 UTC, mikaelmello approved these changes

2018-06-15 03:57 UTC, merged